"""Causal feature engineering for the Phase 4 forecasting pipeline."""

from src.features.selection import (
    CORR_THRESHOLD,
    HUBER_DELTA,
    LEVEL_COLUMN,
    TOP_K,
    TS_WIDTH,
    FoldFeatureSignature,
    apply_fold_signature,
    select_fold_features,
)
from src.features.technical import (
    EPS,
    FEATURE_LAGS,
    MACD_FAST,
    MACD_SIGNAL,
    MACD_SLOW,
    RETURN_LAGS,
    REVIN_STD_FLOOR,
    WINDOWS,
    base_feature_names,
    compute_technical_features,
    revin_causal_rows,
    revin_window,
    technical_feature_names,
)

__all__ = [
    "CORR_THRESHOLD",
    "EPS",
    "FoldFeatureSignature",
    "HUBER_DELTA",
    "LEVEL_COLUMN",
    "FEATURE_LAGS",
    "MACD_FAST",
    "MACD_SIGNAL",
    "MACD_SLOW",
    "RETURN_LAGS",
    "TOP_K",
    "TS_WIDTH",
    "REVIN_STD_FLOOR",
    "WINDOWS",
    "apply_fold_signature",
    "base_feature_names",
    "compute_technical_features",
    "revin_causal_rows",
    "revin_window",
    "select_fold_features",
    "technical_feature_names",
]
